apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pravin
  name: pravin
spec:
  containers:
  - image: nginx
    name: pravinn
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
